apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/ingress.yaml
  - manifests/log-output-deployment.yaml
  - manifests/log-configmap.yaml
  - manifests/ping-pong-deployment.yaml
  - manifests/redis-statefulset.yaml
  - manifests/busybox.yaml

images:
  - name: PROJECT/LOG_IMAGE
    newName: log-output-dep
  - name: PROJECT/PING_IMAGE
    newName: pingpong-dep
